number = int(input("Give me a number from 3 to 10: "))

if number == 3:
    print("Triangle")
elif number == 4:
    print("square")
elif number == 5:
    print("Pentagon")
elif number == 6:
    print("Hexagon")
elif number == 7:
    print("Heptagon")
elif number == 8:
    print("Octagon")
elif number == 9:
    print("Nonagon")
elif number == 10:
    print("Decagon")
else:
    print("Invalid input. Please enter a number between 3 and 10.")
